- name: Cyberarks test quasys
  hosts: all
  collections:
    - cyberark.pas
  tasks:
  - name: Logon to CyberArk Vault using PAS Web Services SDK
    cyberark_authentication:
      api_base_url: https://3.220.135.124
      validate_certs: false
      username: "Administrator"
      password: "CyberArk123!"
