- name: Cyberarks test quasys
  hosts: all
  collections:
    - cyberark.pas
  tasks:
    - name: Logon to CyberArk Vault using PAS Web Services SDK
      cyberark.pas.cyberark_authentication:
        api_base_url: http://components.cyberark.local
        validate_certs: false
        username: "bizdev"
        password: "Cyberark1"
